# Server settings
server.port=8081
logging.level.root=INFO
logging.level.g1.utils.DBConnectorRDF4J=DEBUG

# CORS
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:8080}

# GraphDB
graphdb.repository.uri=http://localhost:7200/repositories/
graphdb.repository.id=CMKEws23_Integration
graphdb.username=${GRAPHDB_USERNAME}
graphdb.password=${GRAPHDB_PASSWORD}

# Jena
jena.dataset.uri=http://localhost:3030/cmke_database/
jena.dataset.username=${JENA_USERNAME}
jena.dataset.password=${JENA_PASSWORD}