description: "This API will be used to train model using generated_drivers.json"
tags:
  - name: Train model
produces:
  - application/json
responses:
    "200":
      description: OK
      schema:
        title: Valid Training Response
        type: object
        example:
          application/json: {'message': 'Model trained successfully'}
    "500":
      description: Internal error
      schema:
        title: Error processing request
        type: object
        example:
          responseCode: 500
          responseDesc: Error processing request